server:
  port: 80

spring:
  datasource:
    druid:
      username: sty
      password: Sty201241
      url: jdbc:mysql://rm-2zeba03v157j6e0syto.mysql.rds.aliyuncs.com:3306/examination_review?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.model.ValueObject

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

